### ISSUE TITLE
keyerror 

### ISSUE THREAD

**Issue by coding-cadenza** [zirui-HIT/DAC#2]
when I ran align.py, an error occurred stating that there is no "alignment" key in the demo.
`Traceback (most recent call last):
  File "/home/miniconda3/envs/flash-attn/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/miniconda3/envs/flash-attn/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/miniconda3/envs/flash-attn/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/text-to-sql/DAC/align.py", line 412, in generate_prompt
    [x['type'] for demo in demos_used for x in demo['alignment']['gold'] if x['type']])
  File "/home/text-to-sql/DAC/align.py", line 412, in <listcomp>
    [x['type'] for demo in demos_used for x in demo['alignment']['gold'] if x['type']])
KeyError: 'alignment'
`

**Comment by zirui-HIT** [comment]
Apologize for our missing, the 'alignment' is built based on the Spider data labeled by [EtA](https://arxiv.org/pdf/2109.10540)
To obtain 'alignment' key, you can:
1. down the data from [EtA paper](https://arxiv.org/pdf/2109.10540);
2. run the following code:
```python
import json

if __name__ == '__main__':
    from align import build_alignment

    with open('EtA_dir/Spider/dev.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    data_dev_aligned = [{
        "db_id": d['schema']['db_id'],
        "question": ' '.join(t['token'] for t in d['question']['tokens']),
        "query": ' '.join(str(t['value']) for t in d['sql']['tokens']),
        "alignment": {"gold": build_alignment(d)}
    } for d in data]
    with open('./result/dev.json', 'w', encoding='utf-8') as f:
        json.dump(data_dev_aligned, f, ensure_ascii=False, indent=4)
```

We will update the preprocess code and the preprocessed data as soon as possible.

**Comment by tyj-wsy** [comment]
针对spider数据集下的dev.json数据运行此代码会出现一定的问题，大概率在build_alignment函数中   
 for t, c in zip(data['question']['tokens'], data['align_labels']):
        entity_aligned = ""
        if not c:
            entity_aligned = None
        elif c['type'] == 'tbl':
            entity_aligned = data['schema']['table_names_original'][int(
                c['id'])]
        elif c['type'] == 'col' or c['type'] == 'val':
            table_idx = data['schema']['column_to_table'][str(c['id'])]
            table_name = data['schema']['table_names_original'][int(table_idx)]
            column_name = data['schema']['column_names_original'][int(c['id'])]
            entity_aligned = f"{table_name}.{column_name}"
        else:
            entity_aligned = None
        result.append({
            "token": t['token'],
            "schema": entity_aligned,
            "type": c['type'] if c else None
        })对于这个函数中，data并没有['align_labels']，也没有 data['schema']['table_names_original']这种类似的键值对，大概率是缺少了对于问题的每个token的详细描述，如token的类型，token的id等，我想知道这个问题解决了没有
